// ECMA-48.h - control functions for coded character sets in 7-bit codes
// https://www.ecma-international.org/publications-and-standards/standards/ecma-48

// Elements of the C0 set

#define ACK "\x06"
#define BEL "\x07"
#define BS  "\x08"
#define CAN "\x18"
#define CR  "\x0d"
#define DC1 "\x11"
#define DC2 "\x12"
#define DC3 "\x13"
#define DC4 "\x14"
#define DLE "\x10"
#define EM  "\x19"
#define ENQ "\x05"
#define EOT "\x04"
#define ESC "\x1b"
#define ETB "\x17"
#define ETX "\x03"
#define FF  "\x0c"
#define HT  "\x09"
#define IS1 "\x1f"
#define IS2 "\x1e"
#define IS3 "\x1d"
#define IS4 "\x1c"
#define LF  "\x0a"
#define LS0 "\x0f"
#define LS1 "\x0e"
#define NAK "\x15"
#define NUL "\x00"
#define SI  "\x0f"
#define SO  "\x0e"
#define SOH "\x01"
#define STX "\x02"
#define SUB "\x1a"
#define SYN "\x16"
#define VT  "\x0b"

// Elements of the C1 set

#define APC ESC "\x5f"
#define BPH ESC "\x42"
#define CCH ESC "\x54"
#define CSI ESC "\x5b"
#define DCS ESC "\x50"
#define EPA ESC "\x57"
#define ESA ESC "\x47"
#define HTJ ESC "\x49"
#define HTS ESC "\x48"
#define MW  ESC "\x55"
#define NBH ESC "\x43"
#define NEL ESC "\x45"
#define OSC ESC "\x5d"
#define PLD ESC "\x4b"
#define PLU ESC "\x4c"
#define PM  ESC "\x5e"
#define PU1 ESC "\x51"
#define PU2 ESC "\x52"
#define RI  ESC "\x4d"
#define SCI ESC "\x5a"
#define SOS ESC "\x58"
#define SPA ESC "\x56"
#define SSA ESC "\x46"
#define SS2 ESC "\x4e"
#define SS3 ESC "\x4f"
#define ST  ESC "\x5c"
#define STS ESC "\x53"
#define VTS ESC "\x4a"

// Independent control functions

#define CMD  ESC "\x64"
#define DMI  ESC "\x60"
#define EMI  ESC "\x62"
#define INT  ESC "\x61"
#define LS1R ESC "\x7e"
#define LS2  ESC "\x6e"
#define LS2R ESC "\x7d"
#define LS3  ESC "\x6f"
#define LS3R ESC "\x7c"
#define RIS  ESC "\x63"

// Control sequences

#define CBT(p)  CSI p "\x5a"
#define CHA(p)  CSI p "\x47"
#define CHT(p)  CSI p "\x49"
#define CNL(p)  CSI p "\x45"
#define CPL(p)  CSI p "\x46"
#define CPR(p)  CSI p "\x52"
#define CTC(p)  CSI p "\x57"
#define CUB(p)  CSI p "\x44"
#define CUD(p)  CSI p "\x42"
#define CUF(p)  CSI p "\x43"
#define CUP(p)  CSI p "\x48"
#define CUU(p)  CSI p "\x41"
#define CVT(p)  CSI p "\x59"
#define DA(p)   CSI p "\x63"
#define DAQ(p)  CSI p "\x6f"
#define DCH(p)  CSI p "\x50"
#define DL(p)   CSI p "\x4d"
#define DSR(p)  CSI p "\x6e"
#define DTA(p)  CSI p "\x20\x54"
#define EA(p)   CSI p "\x4f"
#define ECH(p)  CSI p "\x58"
#define ED(p)   CSI p "\x4a"
#define EF(p)   CSI p "\x4e"
#define EL(p)   CSI p "\x4b"
#define FNK(p)  CSI p "\x20\x57"
#define FNT(p)  CSI p "\x20\x44"
#define GCC(p)  CSI p "\x20\x5f"
#define GSM(p)  CSI p "\x20\x42"
#define GSS(p)  CSI p "\x20\x43"
#define HPA(p)  CSI p "\x60"
#define HPB(p)  CSI p "\x6a"
#define HPR(p)  CSI p "\x61"
#define HVP(p)  CSI p "\x66"
#define ICH(p)  CSI p "\x40"
#define IDCS(p) CSI p "\x20\x4f"
#define IGS(p)  CSI p "\x20\x4d"
#define IL(p)   CSI p "\x4c"
#define JFY(p)  CSI p "\x20\x46"
#define MC(p)   CSI p "\x69"
#define NP(p)   CSI p "\x55"
#define PEC(p)  CSI p "\x20\x5a"
#define PFS(p)  CSI p "\x20\x4a"
#define PP(p)   CSI p "\x56"
#define PPA(p)  CSI p "\x20\x50"
#define PPB(p)  CSI p "\x20\x52"
#define PPR(p)  CSI p "\x20\x51"
#define PTX(p)  CSI p "\x5c"
#define QUAD(p) CSI p "\x20\x48"
#define REP(p)  CSI p "\x62"
#define RM(p)   CSI p "\x6c"
#define SACS(p) CSI p "\x20\x5c"
#define SAPV(p) CSI p "\x20\x5d"
#define SCO(p)  CSI p "\x20\x65"
#define SCP(p)  CSI p "\x20\x6b"
#define SCS(p)  CSI p "\x20\x67"
#define SD(p)   CSI p "\x54"
#define SDS(p)  CSI p "\x5d"
#define SEE(p)  CSI p "\x51"
#define SEF(p)  CSI p "\x20\x59"
#define SGR(p)  CSI p "\x6d"
#define SHS(p)  CSI p "\x20\x4b"
#define SIMD(p) CSI p "\x5e"
#define SL(p)   CSI p "\x20\x40"
#define SLH(p)  CSI p "\x20\x55"
#define SLL(p)  CSI p "\x20\x56"
#define SLS(p)  CSI p "\x20\x68"
#define SM(p)   CSI p "\x68"
#define SPD(p)  CSI p "\x20\x53"
#define SPH(p)  CSI p "\x20\x69"
#define SPI(p)  CSI p "\x20\x47"
#define SPL(p)  CSI p "\x20\x6a"
#define SPQR(p) CSI p "\x20\x58"
#define SR(p)   CSI p "\x20\x41"
#define SRCS(p) CSI p "\x20\x66"
#define SRS(p)  CSI p "\x5b"
#define SSU(p)  CSI p "\x20\x49"
#define SSW(p)  CSI p "\x20\x5b"
#define STAB(p) CSI p "\x20\x5e"
#define SU(p)   CSI p "\x53"
#define SVS(p)  CSI p "\x20\x4c"
#define TAC(p)  CSI p "\x20\x62"
#define TALE(p) CSI p "\x20\x61"
#define TATE(p) CSI p "\x20\x60"
#define TBC(p)  CSI p "\x67"
#define TCC(p)  CSI p "\x20\x63"
#define TSR(p)  CSI p "\x20\x64"
#define TSS(p)  CSI p "\x20\x45"
#define VPA(p)  CSI p "\x64"
#define VPB(p)  CSI p "\x6b"
#define VPR(p)  CSI p "\x65"
