// ecma-48.h - control functions for coded character sets in 7-bit codes
// https://www.ecma-international.org/publications-and-standards/standards/ecma-48

// Elements of the C0 set

#define ACK "\x06"
#define BEL "\x07"
#define BS  "\x08"
#define CAN "\x18"
#define CR  "\x0d"
#define DC1 "\x11"
#define DC2 "\x12"
#define DC3 "\x13"
#define DC4 "\x14"
#define DLE "\x10"
#define EM  "\x19"
#define ENQ "\x05"
#define EOT "\x04"
#define ESC "\x1b"
#define ETB "\x17"
#define ETX "\x03"
#define FF  "\x0c"
#define HT  "\x09"
#define IS1 "\x1f"
#define IS2 "\x1e"
#define IS3 "\x1d"
#define IS4 "\x1c"
#define LF  "\x0a"
#define LS0 "\x0f"
#define LS1 "\x0e"
#define NAK "\x15"
#define NUL "\x00"
#define SI  "\x0f"
#define SO  "\x0e"
#define SOH "\x01"
#define STX "\x02"
#define SUB "\x1a"
#define SYN "\x16"
#define VT  "\x0b"

// Elements of the C1 set

#define APC ESC "_"
#define BPH ESC "B"
#define CCH ESC "T"
#define CSI ESC "["
#define DCS ESC "P"
#define EPA ESC "W"
#define ESA ESC "G"
#define HTJ ESC "I"
#define HTS ESC "H"
#define MW  ESC "U"
#define NBH ESC "C"
#define NEL ESC "E"
#define OSC ESC "]"
#define PLD ESC "K"
#define PLU ESC "L"
#define PM  ESC "^"
#define PU1 ESC "Q"
#define PU2 ESC "R"
#define RI  ESC "M"
#define SCI ESC "Z"
#define SOS ESC "X"
#define SPA ESC "V"
#define SSA ESC "F"
#define SS2 ESC "N"
#define SS3 ESC "O"
#define ST  ESC "\\"
#define STS ESC "S"
#define VTS ESC "J"

// Independent control functions

#define CMD  ESC "d"
#define DMI  ESC "`"
#define EMI  ESC "b"
#define INT  ESC "a"
#define LS1R ESC "~"
#define LS2  ESC "n"
#define LS2R ESC "}"
#define LS3  ESC "o"
#define LS3R ESC "|"
#define RIS  ESC "c"

// Control sequences

#define CBT(p)  CSI p "Z"
#define CHA(p)  CSI p "G"
#define CHT(p)  CSI p "I"
#define CNL(p)  CSI p "E"
#define CPL(p)  CSI p "F"
#define CPR(p)  CSI p "R"
#define CTC(p)  CSI p "W"
#define CUB(p)  CSI p "D"
#define CUD(p)  CSI p "B"
#define CUF(p)  CSI p "C"
#define CUP(p)  CSI p "H"
#define CUU(p)  CSI p "A"
#define CVT(p)  CSI p "Y"
#define DA(p)   CSI p "c"
#define DAQ(p)  CSI p "o"
#define DCH(p)  CSI p "P"
#define DL(p)   CSI p "M"
#define DSR(p)  CSI p "n"
#define DTA(p)  CSI p " T"
#define EA(p)   CSI p "O"
#define ECH(p)  CSI p "X"
#define ED(p)   CSI p "J"
#define EF(p)   CSI p "N"
#define EL(p)   CSI p "K"
#define FNK(p)  CSI p " W"
#define FNT(p)  CSI p " D"
#define GCC(p)  CSI p " _"
#define GSM(p)  CSI p " B"
#define GSS(p)  CSI p " C"
#define HPA(p)  CSI p "`"
#define HPB(p)  CSI p "j"
#define HPR(p)  CSI p "a"
#define HVP(p)  CSI p "f"
#define ICH(p)  CSI p "@"
#define IDCS(p) CSI p " O"
#define IGS(p)  CSI p " M"
#define IL(p)   CSI p "L"
#define JFY(p)  CSI p " F"
#define MC(p)   CSI p "i"
#define NP(p)   CSI p "U"
#define PEC(p)  CSI p " Z"
#define PFS(p)  CSI p " J"
#define PP(p)   CSI p "V"
#define PPA(p)  CSI p " P"
#define PPB(p)  CSI p " R"
#define PPR(p)  CSI p " Q"
#define PTX(p)  CSI p "\\"
#define QUAD(p) CSI p " H"
#define REP(p)  CSI p "b"
#define RM(p)   CSI p "l"
#define SACS(p) CSI p " \\"
#define SAPV(p) CSI p " ]"
#define SCO(p)  CSI p " e"
#define SCP(p)  CSI p " k"
#define SCS(p)  CSI p " g"
#define SD(p)   CSI p "T"
#define SDS(p)  CSI p "]"
#define SEE(p)  CSI p "Q"
#define SEF(p)  CSI p " Y"
#define SGR(p)  CSI p "m"
#define SHS(p)  CSI p " K"
#define SIMD(p) CSI p "^"
#define SL(p)   CSI p " @"
#define SLH(p)  CSI p " U"
#define SLL(p)  CSI p " V"
#define SLS(p)  CSI p " h"
#define SM(p)   CSI p "h"
#define SPD(p)  CSI p " S"
#define SPH(p)  CSI p " i"
#define SPI(p)  CSI p " G"
#define SPL(p)  CSI p " j"
#define SPQR(p) CSI p " X"
#define SR(p)   CSI p " A"
#define SRCS(p) CSI p " f"
#define SRS(p)  CSI p "["
#define SSU(p)  CSI p " I"
#define SSW(p)  CSI p " ["
#define STAB(p) CSI p " ^"
#define SU(p)   CSI p "S"
#define SVS(p)  CSI p " L"
#define TAC(p)  CSI p " b"
#define TALE(p) CSI p " a"
#define TATE(p) CSI p " `"
#define TBC(p)  CSI p "g"
#define TCC(p)  CSI p " c"
#define TSR(p)  CSI p " d"
#define TSS(p)  CSI p " E"
#define VPA(p)  CSI p "d"
#define VPB(p)  CSI p "k"
#define VPR(p)  CSI p "e"
